name: Update Certifications JSON

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Nombre de la certificación"
        required: true
      provider:
        description: "Proveedor"
        required: true
      iconName:
        description: "Icono (Formato Iconify (icon-[devicon-plain--kotlin))"
        required: true
      iconColor:
        description: "Color del icono (Formato Tailwind (text-purple-600))"
        required: true
      issueDate:
        description: "Fecha de emisión (Formato: 01 Enero 2000)"
        required: true
permissions:
  contents: write
  pull-requests: write

jobs:
  update-certifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Update certifications.json
        run: |
          FILE="src/assets/data/certifications.json"

          node -e "
          const fs = require('fs');
          const file = '$FILE';

          let data = [];

          if (fs.existsSync(file)) {
            data = JSON.parse(fs.readFileSync(file, 'utf-8'));
          }

          if (!Array.isArray(data)) {
            throw new Error('certifications.json debe ser un array');
          }

          const newItem = {
            name: '${{ github.event.inputs.name }}',
            provider: '${{ github.event.inputs.provider }}',
            icon: { name: '${{ github.event.inputs.iconName }}', color: '${{ github.event.inputs.iconColor }}' },
            issueDate: '${{ github.event.inputs.issueDate }}',
          };

          data.push(newItem);

          fs.writeFileSync(file, JSON.stringify(data, null, 2));
          "

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat: se añade ${{github.event.inputs.name}}"
          branch: "update/certification-${{ github.run_id }}"
          title: "Nueva certificación: ${{github.event.inputs.name}}"
          body: "Automated update to certification.json"
