name: Update Degrees

on:
  workflow_dispatch:
    inputs:
      institution:
        description: "Institución"
        required: true
      degree:
        description: "Carrera"
        required: true
      period:
        description: "Periodo (ej: Mar. 2024 – Nov. 2025)"
        required: true
      description:
        description: "Descripción"
        required: true
permissions:
  contents: write
  pull-requests: write

jobs:
  update-degrees:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Update degrees.json
        run: |
          FILE="src/assets/data/degrees.json"

          node -e "
          const fs = require('fs');
          const file = '$FILE';

          let data = [];

          if (fs.existsSync(file)) {
            data = JSON.parse(fs.readFileSync(file, 'utf-8'));
          }

          if (!Array.isArray(data)) {
            throw new Error('degrees.json debe ser un array');
          }

          const newItem = {
            institution: '${{ github.event.inputs.institution }}',
            degree: '${{ github.event.inputs.degree }}',
            period: '${{ github.event.inputs.period }}',
            description: '${{ github.event.inputs.description }}'
          };

          const objectIndex = data.findIndex(degree => degree.name === newItem.name)

          if(objectIndex != -1){
            data[objectIndex] = newItem
          }
          else{
            data.push(newItem)
          }
          fs.writeFileSync(file, JSON.stringify(data, null, 2));
          "

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat: se añade ${{github.event.inputs.degree}}"
          branch: "update/degrees-${{ github.run_id }}"
          title: "Se añade ${{github.event.inputs.degree}}"
          body: "Automated update to degrees.json"
