name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  deploy:
    uses: RobertoVillalon/.github/shared-workflows/deployAngularToGithubPages.yml
    with:
      base_href: "/portfolio/"
      publish_dir: "./dist/portfolio/browser"
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
