name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  deploy:
    uses: RobertoVillalon/infraestructura/.github/workflows/deployAngularToGithubPages.yml@main
    with:
      base_href: "/portfolio/"
      publish_dir: "./dist/portfolio/browser"
      environment_keys: "MAPBOX_TOKEN"
